language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]
    then
      rustup component add rustfmt
      cargo fmt --all -- --check
    fi
  - cargo build --verbose --all-targets
  - cargo test --verbose
