[workspace]

members = [
    "pijama_ast",
    "pijama_parser",
    "pijama_ty",
    "pijama_mir",
    "pijama_tycheck",
    "pijama_lir",
    "pijama_llama",
    "pijama_machine",
    "pijama_driver",
    "pijama",
]
